[project]
name = "data-publish-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mysql-connector-python>=9.0.0",
    "pyiceberg[s3fs,pyarrow]>=0.7.0",
    "pyarrow>=17.0.0",
    "faker>=40.1.0",
    "polars>=1.37.1",
]

[tool.pyrefly]
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]
