[project]
name = "etl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pyiceberg[pyarrow,s3fs]>=0.7.0",
    "requests>=2.32.5",
    "polars>=1.0.0",
    "connectorx>=0.3.0",
    "typer>=0.12.0",
]

[tool.pyrefly]
project-includes = [
    "**/*.py*",
    "**/*.ipynb",
]

[project.scripts]
etl = "main:app"
