-- ============================================================================
-- Mixpanel Event Data Table Structure
-- ============================================================================
-- This DDL mirrors the exact structure of Mixpanel's Raw Event Export API response
-- and includes all default properties collected by Mixpanel SDKs and APIs.
-- 
-- Mixpanel events are stored as JSON with two main components:
--   1. "event" - The event name
--   2. "properties" - A dictionary of all event properties
--
-- Reference: https://developer.mixpanel.com/reference/raw-event-export
--            https://docs.mixpanel.com/docs/data-structure/property-reference/default-properties
-- ============================================================================

-- ============================================================================
-- MAIN EVENTS TABLE (Mirrors Mixpanel Export API Response)
-- ============================================================================
CREATE TABLE mixpanel_events (
    -- ========================================================================
    -- INTERNAL IDENTIFIERS (for database management)
    -- ========================================================================
    id                          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    
    -- ========================================================================
    -- CORE MIXPANEL EVENT STRUCTURE
    -- ========================================================================
    -- The event name (e.g., "Signed Up", "Purchase", "Page View")
    event                       VARCHAR(255) NOT NULL COMMENT 'The name of the event',
    
    -- ========================================================================
    -- REQUIRED PROPERTIES
    -- ========================================================================
    -- Mixpanel project token
    token                       VARCHAR(64) NOT NULL COMMENT 'Mixpanel project token',
    
    -- Event timestamp (Unix timestamp in milliseconds)
    `time`                      BIGINT NOT NULL COMMENT 'Unix timestamp (ms) when event occurred',
    time_datetime               DATETIME(3) AS (FROM_UNIXTIME(`time` / 1000)) STORED COMMENT 'Converted datetime from time',
    
    -- Unique user identifier
    distinct_id                 VARCHAR(255) NOT NULL COMMENT 'Unique identifier for the user',
    
    -- Event deduplication ID
    `$insert_id`                VARCHAR(128) COMMENT 'Unique event ID for deduplication (UUID recommended)',
    
    -- ========================================================================
    -- USER IDENTITY PROPERTIES
    -- ========================================================================
    `$device_id`                VARCHAR(255) COMMENT 'Autogenerated device-local ID',
    `$user_id`                  VARCHAR(255) COMMENT 'Identified user ID (set via identify())',
    `$anon_id`                  VARCHAR(255) COMMENT 'Anonymous ID before identification',
    
    -- ========================================================================
    -- GEOLOCATION PROPERTIES (Derived from IP)
    -- ========================================================================
    ip                          VARCHAR(45) COMMENT 'IP address (used for geolocation, then discarded)',
    `$city`                     VARCHAR(255) COMMENT 'City parsed from IP',
    `$region`                   VARCHAR(255) COMMENT 'Region/State parsed from IP',
    mp_country_code             CHAR(2) COMMENT 'Country code (ISO 3166-1 alpha-2) parsed from IP',
    `$timezone`                 VARCHAR(100) COMMENT 'Timezone parsed from IP',
    `$latitude`                 DECIMAL(10, 8) COMMENT 'Latitude coordinate',
    `$longitude`                DECIMAL(11, 8) COMMENT 'Longitude coordinate',
    `$geo_source`               VARCHAR(50) COMMENT 'Source of geolocation (e.g., reverse_geocoding)',
    
    -- ========================================================================
    -- LIBRARY & SDK PROPERTIES
    -- ========================================================================
    mp_lib                      VARCHAR(50) COMMENT 'Mixpanel library: web, android, iphone, swift, unity, react-native, flutter',
    `$lib_version`              VARCHAR(20) COMMENT 'Mixpanel library version',
    mp_sent_by_lib_version      VARCHAR(20) COMMENT 'Library version that sent the data (JS SDK)',
    
    -- ========================================================================
    -- DEVICE PROPERTIES
    -- ========================================================================
    `$os`                       VARCHAR(50) COMMENT 'Operating system',
    `$os_version`               VARCHAR(50) COMMENT 'OS version',
    `$device`                   VARCHAR(100) COMMENT 'Device name (mobile web)',
    `$manufacturer`             VARCHAR(100) COMMENT 'Device manufacturer',
    `$brand`                    VARCHAR(100) COMMENT 'Device brand',
    `$model`                    VARCHAR(100) COMMENT 'Device model',
    `$watch_model`              VARCHAR(100) COMMENT 'iOS Watch model',
    `$screen_height`            INT UNSIGNED COMMENT 'Screen height in pixels/points',
    `$screen_width`             INT UNSIGNED COMMENT 'Screen width in pixels/points',
    `$screen_dpi`               INT UNSIGNED COMMENT 'Screen pixel density (DPI)',
    
    -- ========================================================================
    -- BROWSER PROPERTIES (Web SDK)
    -- ========================================================================
    `$browser`                  VARCHAR(100) COMMENT 'Browser name',
    `$browser_version`          VARCHAR(50) COMMENT 'Browser version',
    
    -- ========================================================================
    -- APP PROPERTIES (Mobile SDKs)
    -- ========================================================================
    `$app_build_number`         VARCHAR(50) COMMENT 'App build number',
    `$app_version_string`       VARCHAR(50) COMMENT 'App version string',
    `$app_version`              VARCHAR(50) COMMENT 'App version',
    `$app_release`              VARCHAR(50) COMMENT 'App release version',
    `$app_namespace`            VARCHAR(255) COMMENT 'App bundle ID / namespace',
    
    -- ========================================================================
    -- NETWORK PROPERTIES
    -- ========================================================================
    `$carrier`                  VARCHAR(100) COMMENT 'Wireless carrier',
    `$radio`                    VARCHAR(20) COMMENT 'Cellular network type (3G, 4G, LTE, 5G)',
    `$wifi`                     TINYINT(1) COMMENT 'WiFi connection active',
    `$bluetooth_enabled`        TINYINT(1) COMMENT 'Bluetooth enabled',
    `$bluetooth_version`        VARCHAR(20) COMMENT 'Bluetooth version (none, ble, classic)',
    `$has_nfc`                  TINYINT(1) COMMENT 'Device supports NFC',
    `$has_telephone`            TINYINT(1) COMMENT 'Device has telephone capability',
    `$google_play_services`     VARCHAR(50) COMMENT 'Google Play Services status',
    
    -- ========================================================================
    -- WEB REFERRER & URL PROPERTIES (JS SDK)
    -- ========================================================================
    `$current_url`              TEXT COMMENT 'URL where event was tracked',
    `$initial_referrer`         TEXT COMMENT 'Referrer URL on first visit (or $direct)',
    `$initial_referring_domain` VARCHAR(255) COMMENT 'Referring domain on first visit (or $direct)',
    `$referrer`                 TEXT COMMENT 'Current referring URL',
    `$referring_domain`         VARCHAR(255) COMMENT 'Current referring domain',
    `$search_engine`            VARCHAR(100) COMMENT 'Search engine used to arrive',
    mp_keyword                  VARCHAR(255) COMMENT 'Search keywords from referrer URL',
    
    -- ========================================================================
    -- UTM CAMPAIGN TRACKING PROPERTIES
    -- ========================================================================
    utm_source                  VARCHAR(255) COMMENT 'UTM source parameter',
    utm_medium                  VARCHAR(255) COMMENT 'UTM medium parameter',
    utm_campaign                VARCHAR(255) COMMENT 'UTM campaign parameter',
    utm_content                 VARCHAR(255) COMMENT 'UTM content parameter',
    utm_term                    VARCHAR(255) COMMENT 'UTM term parameter',
    utm_id                      VARCHAR(255) COMMENT 'UTM ID parameter',
    utm_source_platform         VARCHAR(255) COMMENT 'UTM source platform',
    utm_creative_format         VARCHAR(255) COMMENT 'UTM creative format',
    utm_marketing_tactic        VARCHAR(255) COMMENT 'UTM marketing tactic',
    
    -- ========================================================================
    -- INITIAL UTM PROPERTIES (First Touch Attribution)
    -- ========================================================================
    initial_utm_source          VARCHAR(255) COMMENT 'First UTM source seen',
    initial_utm_medium          VARCHAR(255) COMMENT 'First UTM medium seen',
    initial_utm_campaign        VARCHAR(255) COMMENT 'First UTM campaign seen',
    initial_utm_content         VARCHAR(255) COMMENT 'First UTM content seen',
    initial_utm_term            VARCHAR(255) COMMENT 'First UTM term seen',
    
    -- ========================================================================
    -- TIMING & DURATION PROPERTIES
    -- ========================================================================
    `$duration`                 DECIMAL(18, 4) COMMENT 'Elapsed time (seconds) between time_event and track call',
    
    -- ========================================================================
    -- API & PROCESSING METADATA
    -- ========================================================================
    `$mp_api_endpoint`          VARCHAR(100) COMMENT 'API endpoint used: api.mixpanel.com, api-eu.mixpanel.com, api-in.mixpanel.com, api-js.mixpanel.com',
    `$mp_api_timestamp_ms`      BIGINT COMMENT 'UTC timestamp (ms) when event received by API',
    mp_processing_time_ms       BIGINT COMMENT 'UTC timestamp (ms) when event processed',
    `$import`                   TINYINT(1) COMMENT 'True if sent via /import API',
    
    -- ========================================================================
    -- SESSION PROPERTIES
    -- ========================================================================
    `$session_id`               VARCHAR(128) COMMENT 'Session identifier',
    `$event_count`              INT UNSIGNED COMMENT 'Event count within session',
    
    -- ========================================================================
    -- PAGE/SCREEN VIEW PROPERTIES
    -- ========================================================================
    `$screen_name`              VARCHAR(255) COMMENT 'Screen/View name (mobile)',
    `$page_name`                VARCHAR(255) COMMENT 'Page name (web)',
    `$title`                    VARCHAR(500) COMMENT 'Page title',
    
    -- ========================================================================
    -- MIXPANEL INTERNAL PROPERTIES
    -- ========================================================================
    mp_original_distinct_id     VARCHAR(255) COMMENT 'Original distinct_id before merge',
    mp_original_event_name      VARCHAR(255) COMMENT 'Original event name before mapping',
    `$identified_id`            VARCHAR(255) COMMENT 'Identified ID from identity merge',
    `$alias`                    VARCHAR(255) COMMENT 'Alias ID',
    
    -- ========================================================================
    -- GROUP ANALYTICS PROPERTIES
    -- ========================================================================
    `$group_id`                 VARCHAR(255) COMMENT 'Group identifier for group analytics',
    `$group_key`                VARCHAR(255) COMMENT 'Group key name',
    
    -- ========================================================================
    -- EXPERIMENT / FEATURE FLAG PROPERTIES
    -- ========================================================================
    `$experiment_id`            VARCHAR(128) COMMENT 'Experiment/Feature flag ID',
    `$variant_id`               VARCHAR(128) COMMENT 'Variant ID in experiment',
    `$experiment_name`          VARCHAR(255) COMMENT 'Experiment name',
    `$variant_name`             VARCHAR(255) COMMENT 'Variant name',
    
    -- ========================================================================
    -- REVENUE PROPERTIES (for revenue analytics)
    -- ========================================================================
    `$revenue`                  DECIMAL(18, 4) COMMENT 'Revenue amount',
    `$price`                    DECIMAL(18, 4) COMMENT 'Item price',
    `$quantity`                 INT COMMENT 'Item quantity',
    `$currency`                 CHAR(3) COMMENT 'Currency code (ISO 4217)',
    
    -- ========================================================================
    -- CUSTOM PROPERTIES (Flexible JSON Storage)
    -- ========================================================================
    -- All additional custom properties sent with the event
    properties                  JSON COMMENT 'Full properties object as JSON (for custom properties)',
    
    -- ========================================================================
    -- DATA WAREHOUSE METADATA
    -- ========================================================================
    _ingested_at                DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) COMMENT 'When record was ingested into warehouse',
    _updated_at                 DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3) COMMENT 'Last update timestamp',
    _source_file                VARCHAR(500) COMMENT 'Source file/batch identifier',
    _batch_id                   VARCHAR(128) COMMENT 'Ingestion batch ID',
    
    -- ========================================================================
    -- INDEXES
    -- ========================================================================
    
    -- Deduplication index (Mixpanel uses event, time, distinct_id, $insert_id)
    UNIQUE INDEX idx_dedup (event(100), `time`, distinct_id(100), `$insert_id`(64)),
    
    -- Primary lookup indexes
    INDEX idx_distinct_id (distinct_id),
    INDEX idx_user_id (`$user_id`),
    INDEX idx_device_id (`$device_id`),
    INDEX idx_insert_id (`$insert_id`),
    
    -- Event analysis indexes
    INDEX idx_event (event),
    INDEX idx_event_time (event, `time` DESC),
    INDEX idx_time (`time` DESC),
    INDEX idx_time_datetime (time_datetime DESC),
    
    -- User journey indexes
    INDEX idx_distinct_id_time (distinct_id, `time` DESC),
    INDEX idx_distinct_id_event (distinct_id, event, `time` DESC),
    
    -- Geolocation indexes
    INDEX idx_country (mp_country_code),
    INDEX idx_city (`$city`(100)),
    INDEX idx_region (`$region`(100)),
    
    -- Platform/Device indexes
    INDEX idx_lib (mp_lib),
    INDEX idx_os (`$os`),
    INDEX idx_browser (`$browser`),
    INDEX idx_app_version (`$app_version_string`),
    
    -- Campaign attribution indexes
    INDEX idx_utm_source (utm_source(100)),
    INDEX idx_utm_campaign (utm_campaign(100)),
    INDEX idx_utm_combined (utm_source(50), utm_medium(50), utm_campaign(50)),
    
    -- Revenue analysis
    INDEX idx_revenue (`$revenue`),
    
    -- API endpoint analysis
    INDEX idx_api_endpoint (`$mp_api_endpoint`),
    
    -- Session analysis
    INDEX idx_session (`$session_id`),
    
    -- Group analytics
    INDEX idx_group (`$group_key`, `$group_id`)
    
) ENGINE=InnoDB 
  DEFAULT CHARSET=utf8mb4 
  COLLATE=utf8mb4_unicode_ci
  ROW_FORMAT=DYNAMIC
  COMMENT='Mixpanel events table mirroring Raw Event Export API structure';


-- ============================================================================
-- FUNCTIONAL INDEXES ON JSON PROPERTIES (MySQL 8.0+)
-- ============================================================================

-- Example: Index a specific custom property from JSON
-- ALTER TABLE mixpanel_events ADD INDEX idx_custom_plan_type (
--     (CAST(properties->>'$.plan_type' AS CHAR(50) COLLATE utf8mb4_unicode_ci))
-- );


-- ============================================================================
-- USER PROFILES TABLE (Mirrors Mixpanel User Profile Structure)
-- ============================================================================
CREATE TABLE mixpanel_user_profiles (
    -- ========================================================================
    -- INTERNAL IDENTIFIER
    -- ========================================================================
    id                          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    
    -- ========================================================================
    -- CORE IDENTITY
    -- ========================================================================
    distinct_id                 VARCHAR(255) NOT NULL COMMENT 'Unique user identifier',
    
    -- ========================================================================
    -- GEOLOCATION PROPERTIES (Auto-collected)
    -- ========================================================================
    `$city`                     VARCHAR(255) COMMENT 'City of user',
    `$region`                   VARCHAR(255) COMMENT 'Region/State of user',
    `$country_code`             CHAR(2) COMMENT 'Country code (ISO 3166-1 alpha-2)',
    `$timezone`                 VARCHAR(100) COMMENT 'User timezone',
    `$geo_source`               VARCHAR(50) COMMENT 'Geolocation source (reverse_geocoding)',
    
    -- ========================================================================
    -- SYSTEM PROPERTIES (Auto-collected by SDKs)
    -- ========================================================================
    `$last_seen`                DATETIME(3) COMMENT 'Last time profile was updated (auto-set)',
    `$created`                  DATETIME(3) COMMENT 'Profile creation timestamp',
    
    -- Library versions
    `$lib_version`              VARCHAR(20) COMMENT 'Last Mixpanel library version',
    `$android_lib_version`      VARCHAR(20) COMMENT 'Last Android library version',
    `$ios_lib_version`          VARCHAR(20) COMMENT 'Last iOS library version',
    `$swift_lib_version`        VARCHAR(20) COMMENT 'Last Swift library version',
    
    -- OS Properties
    `$os`                       VARCHAR(50) COMMENT 'Last OS',
    `$android_os`               VARCHAR(50) COMMENT 'Android OS (when used)',
    `$android_os_version`       VARCHAR(50) COMMENT 'Last Android OS version',
    `$ios_version`              VARCHAR(50) COMMENT 'Last iOS version',
    
    -- Browser Properties
    `$browser`                  VARCHAR(100) COMMENT 'Last browser',
    `$browser_version`          VARCHAR(50) COMMENT 'Last browser version',
    
    -- App Version Properties
    `$android_app_version`      VARCHAR(50) COMMENT 'Android app version (versionName)',
    `$android_app_version_code` VARCHAR(50) COMMENT 'Android app version code',
    `$ios_app_release`          VARCHAR(50) COMMENT 'iOS app release (CFBundleShortVersionString)',
    `$ios_app_version`          VARCHAR(50) COMMENT 'iOS app version (CFBundleVersion)',
    
    -- Device Properties
    `$android_manufacturer`     VARCHAR(100) COMMENT 'Android device manufacturer',
    `$android_brand`            VARCHAR(100) COMMENT 'Android device brand',
    `$android_model`            VARCHAR(100) COMMENT 'Android device model',
    `$ios_device_model`         VARCHAR(100) COMMENT 'iOS device model',
    
    -- ========================================================================
    -- ATTRIBUTION PROPERTIES (First Touch - JS SDK)
    -- ========================================================================
    `$initial_referrer`         TEXT COMMENT 'Referrer URL on first visit',
    `$initial_referring_domain` VARCHAR(255) COMMENT 'Referring domain on first visit',
    initial_utm_source          VARCHAR(255) COMMENT 'First UTM source',
    initial_utm_medium          VARCHAR(255) COMMENT 'First UTM medium',
    initial_utm_campaign        VARCHAR(255) COMMENT 'First UTM campaign',
    initial_utm_content         VARCHAR(255) COMMENT 'First UTM content',
    initial_utm_term            VARCHAR(255) COMMENT 'First UTM term',
    
    -- ========================================================================
    -- COMMON USER PROPERTIES (Set by application)
    -- ========================================================================
    `$email`                    VARCHAR(320) COMMENT 'User email address',
    `$phone`                    VARCHAR(50) COMMENT 'User phone number',
    `$name`                     VARCHAR(255) COMMENT 'User full name',
    `$first_name`               VARCHAR(100) COMMENT 'User first name',
    `$last_name`                VARCHAR(100) COMMENT 'User last name',
    `$avatar`                   TEXT COMMENT 'User avatar URL',
    
    -- ========================================================================
    -- CUSTOM PROFILE PROPERTIES (Flexible JSON Storage)
    -- ========================================================================
    properties                  JSON COMMENT 'All profile properties as JSON',
    
    -- ========================================================================
    -- METADATA
    -- ========================================================================
    _ingested_at                DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    _updated_at                 DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    
    -- ========================================================================
    -- INDEXES
    -- ========================================================================
    UNIQUE INDEX idx_distinct_id (distinct_id),
    INDEX idx_email (`$email`),
    INDEX idx_phone (`$phone`),
    INDEX idx_name (`$name`(100)),
    INDEX idx_last_seen (`$last_seen`),
    INDEX idx_created (`$created`),
    INDEX idx_country (`$country_code`),
    INDEX idx_city (`$city`(100))
    
) ENGINE=InnoDB 
  DEFAULT CHARSET=utf8mb4 
  COLLATE=utf8mb4_unicode_ci
  ROW_FORMAT=DYNAMIC
  COMMENT='Mixpanel user profiles table';


-- ============================================================================
-- GROUP PROFILES TABLE (Mirrors Mixpanel Group Analytics Structure)
-- ============================================================================
CREATE TABLE mixpanel_group_profiles (
    id                          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    
    -- Group identity
    group_key                   VARCHAR(255) NOT NULL COMMENT 'Group key name (e.g., company_id)',
    group_id                    VARCHAR(255) NOT NULL COMMENT 'Group identifier value',
    
    -- Common group properties
    `$name`                     VARCHAR(255) COMMENT 'Group name',
    
    -- All group properties as JSON
    properties                  JSON COMMENT 'All group properties',
    
    -- Metadata
    _ingested_at                DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    _updated_at                 DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    
    UNIQUE INDEX idx_group (group_key, group_id),
    INDEX idx_group_key (group_key),
    INDEX idx_group_name (`$name`(100))
    
) ENGINE=InnoDB 
  DEFAULT CHARSET=utf8mb4 
  COLLATE=utf8mb4_unicode_ci
  COMMENT='Mixpanel group profiles for group analytics';


-- ============================================================================
-- LOOKUP TABLES (Mirrors Mixpanel Lookup Tables Structure)
-- ============================================================================
CREATE TABLE mixpanel_lookup_tables (
    id                          BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    
    -- Lookup table metadata
    lookup_table_name           VARCHAR(255) NOT NULL COMMENT 'Name of the lookup table',
    join_key                    VARCHAR(255) NOT NULL COMMENT 'The key used to join with events',
    join_value                  VARCHAR(255) NOT NULL COMMENT 'The value of the join key',
    
    -- Lookup properties as JSON
    properties                  JSON COMMENT 'All lookup table properties',
    
    -- Metadata
    _ingested_at                DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    _updated_at                 DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    
    UNIQUE INDEX idx_lookup (lookup_table_name, join_key, join_value),
    INDEX idx_table_name (lookup_table_name),
    INDEX idx_join_key (join_key)
    
) ENGINE=InnoDB 
  DEFAULT CHARSET=utf8mb4 
  COLLATE=utf8mb4_unicode_ci
  COMMENT='Mixpanel lookup tables for dimension enrichment';


-- ============================================================================
-- VIEWS FOR COMMON MIXPANEL ANALYTICS
-- ============================================================================

-- Daily Active Users (DAU)
CREATE OR REPLACE VIEW v_mixpanel_dau AS
SELECT 
    DATE(time_datetime) AS event_date,
    COUNT(DISTINCT distinct_id) AS daily_active_users,
    COUNT(*) AS total_events
FROM mixpanel_events
GROUP BY DATE(time_datetime)
ORDER BY event_date DESC;


-- Event Counts by Name
CREATE OR REPLACE VIEW v_mixpanel_event_counts AS
SELECT 
    event,
    DATE(time_datetime) AS event_date,
    COUNT(*) AS event_count,
    COUNT(DISTINCT distinct_id) AS unique_users
FROM mixpanel_events
GROUP BY event, DATE(time_datetime)
ORDER BY event_date DESC, event_count DESC;


-- Platform Distribution
CREATE OR REPLACE VIEW v_mixpanel_platform_stats AS
SELECT 
    mp_lib AS platform,
    `$os` AS operating_system,
    DATE(time_datetime) AS event_date,
    COUNT(*) AS event_count,
    COUNT(DISTINCT distinct_id) AS unique_users
FROM mixpanel_events
GROUP BY mp_lib, `$os`, DATE(time_datetime)
ORDER BY event_date DESC, event_count DESC;


-- Geographic Distribution
CREATE OR REPLACE VIEW v_mixpanel_geo_stats AS
SELECT 
    mp_country_code AS country,
    `$region` AS region,
    `$city` AS city,
    DATE(time_datetime) AS event_date,
    COUNT(*) AS event_count,
    COUNT(DISTINCT distinct_id) AS unique_users
FROM mixpanel_events
WHERE mp_country_code IS NOT NULL
GROUP BY mp_country_code, `$region`, `$city`, DATE(time_datetime)
ORDER BY event_date DESC, event_count DESC;


-- UTM Campaign Performance
CREATE OR REPLACE VIEW v_mixpanel_campaign_performance AS
SELECT 
    utm_source,
    utm_medium,
    utm_campaign,
    DATE(time_datetime) AS event_date,
    COUNT(*) AS event_count,
    COUNT(DISTINCT distinct_id) AS unique_users
FROM mixpanel_events
WHERE utm_source IS NOT NULL
GROUP BY utm_source, utm_medium, utm_campaign, DATE(time_datetime)
ORDER BY event_date DESC, unique_users DESC;


-- Revenue Summary
CREATE OR REPLACE VIEW v_mixpanel_revenue AS
SELECT 
    DATE(time_datetime) AS event_date,
    event,
    `$currency` AS currency,
    COUNT(*) AS transaction_count,
    COUNT(DISTINCT distinct_id) AS unique_customers,
    SUM(`$revenue`) AS total_revenue,
    AVG(`$revenue`) AS avg_revenue,
    MIN(`$revenue`) AS min_revenue,
    MAX(`$revenue`) AS max_revenue
FROM mixpanel_events
WHERE `$revenue` IS NOT NULL
GROUP BY DATE(time_datetime), event, `$currency`
ORDER BY event_date DESC, total_revenue DESC;


-- ============================================================================
-- SAMPLE JSON STRUCTURE (for reference)
-- ============================================================================
/*
Mixpanel Raw Event Export API returns events in this format (NDJSON - newline delimited JSON):

{
    "event": "Signed Up",
    "properties": {
        "token": "your_project_token",
        "time": 1601412131000,
        "distinct_id": "user@example.com",
        "$insert_id": "5d958f87-542d-4c10-9422-0ed75893dc81",
        "$device_id": "17a8b4f1c2e3d456",
        "$user_id": "user@example.com",
        "ip": "203.0.113.9",
        "$city": "San Francisco",
        "$region": "California",
        "mp_country_code": "US",
        "$os": "Mac OS X",
        "$browser": "Chrome",
        "$browser_version": "91.0.4472.124",
        "mp_lib": "web",
        "$lib_version": "2.45.0",
        "$current_url": "https://example.com/signup",
        "$referrer": "https://google.com/search",
        "$referring_domain": "google.com",
        "utm_source": "google",
        "utm_medium": "cpc",
        "utm_campaign": "summer_sale",
        "$screen_height": 1080,
        "$screen_width": 1920,
        "plan_type": "premium",
        "signup_method": "email"
    }
}

User Profile Structure:
{
    "$distinct_id": "user@example.com",
    "$properties": {
        "$email": "user@example.com",
        "$name": "John Doe",
        "$created": "2024-01-15T10:30:00",
        "$last_seen": "2024-01-20T14:22:00",
        "plan": "premium",
        "company": "Acme Corp"
    }
}
*/
